name: Deploy astrakhan-bases

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ASTRAKHAN_BASES_HOST }}
          username: ${{ secrets.ASTRAKHAN_BASES_USER }}
          key: ${{ secrets.ASTRAKHAN_BASES_KEY }}
          script: |
            #Переключаемся в нужную папку
            cd ~/astrahan-bases/public_html
            
            #Клинируем репозиторий в папку (только для первой выгрузки!!!)
            #git clone https://github.com/site100ru/astrakhan-bases.git .
            
            #Клинируем репозиторий в папку
            git pull
            
            #Если кто то изменил файлы на сервере минуя GitHub, перезаписываем версию на сервере из GitHub
            #git reset --hard HEAD
            #git pull origin main